site_name: Deconvolución de stacks de imágenes del Nanolive 3D

theme:
  name: journal


nav:
  - 'index.md'
  - 'methods.md'
  - 'conclusions.md'
  - 'anexo.md'
  - Página desarrollada con MkDocs: 'ayuda_mkdocs.md'


# para ecuaciones en mathjax
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
#----------------------------------------


markdown_extensions:
#-------IMAGENES y FIGURAS-----------------
# https://squidfunk.github.io/mkdocs-material/reference/images/
  - attr_list
  - md_in_html
# ----- ECUACIONES EN LATEX--------------
# https://squidfunk.github.io/mkdocs-material/reference/math/
  - pymdownx.arithmatex:
      generic: true
  
  - footnotes
#----------------------------------------



plugins:
  - caption:
      additional_identifier: ["Figura", "Ejemplo"]   # para numerar y referenciar figuras y tablas
  - search
  - bibtex:
      bib_file: "docs/biblio.bib"



